# Site
# repository: sproogen/resume-theme
repository: peter-dye/peter-dye.github.io
favicon: images/favicon.ico

# Personal info
name: Peter Dye
title: ECE Student at University of Waterloo
email: peter.dye@uwaterloo.ca
website: peter-dye.github.io

# Social links
# twitter_username: facespics
github_username: peter-dye
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Peter and I am a fourth year student at UWaterloo. I'm studying Electrical Engineering with an Option in Computer Engineering.

  I am most skilled in: <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:
   - Flying airplanes and sailplanes; I have two pilots licenses!
   - Cooking and baking; I love trying new techniques and working with new ingredients
   - Reading and learning; I enjoy a good book, expecially sci-fi, and love to investigate new things

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
