# Site
# original repository was sproogen/modern-resume-theme
repository: peter-dye/peter-dye.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Peter Dye
title: Professional Software Developer
email: peter.dye@uwaterloo.ca
website: peter-dye.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: example
github_username: peter-dye
# dribbble_username: example
# facebook_username: example
# flickr_username: example
# instagram_username: example
# linkedin_username: example
# pinterest_username: example
# youtube_username: example
# googleplus_username: example

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Peter and I am a Professional Software Developer, recently graduated from UWaterloo. I studied Electrical Engineering with an Option in Computer Engineering and now I work as a Software Developer with Brock Solutions.

  I have experience in a whole variety of areas! Some of my favourites include <mark>Python</mark> and the <mark>SciPy</mark> ecosystem, <mark>MATLAB</mark> and <mark>Octave</mark>, <mark>Linux</mark> and <mark>open source software</mark>, <mark>relational databases</mark> and <mark>SQL</mark>, and <mark>algorithms</mark>!

  I am also comfortable with <mark>Git</mark> and <mark>Github</mark>, <mark>C</mark>, <mark>C++</mark>, and <mark>Java</mark>. Of course, I'm quite profficient in <mark>Microsoft Office</mark>, especially <mark>Word</mark> and <mark>Excel</mark>.

  I have good <mark>communication skills</mark> that have been proven many times. I have had outstanding results on technical reports and presentations, and even won an award for the quality of writing in one of my reports! I regularly work in and lead many teams, both for school activities and work projects.

  Some courses that I have really enjoyed (and done well in) are:
    - Operating Systems and Systems Programming
    - Compilers
    - Database Systems
    - Robot Dynamics and Control
    - Computer Security
    - Cooperative and Adaptive Algorithms

content:

- title: Projects
  layout: list
  content:

    - layout: top-middle
      # border: weak
      title: ButtBot
      # link: github.com/peter-dye/ButtBot
      # link_text: Link Text
      additional_links:
        - title: peter-dye/ButtBot
          icon: fab fa-github
          url: github.com/peter-dye/ButtBot
      quote: >
        An autonomous cigarette butt collection and disposal robot.
      description: | # this will include new lines to allow paragraphs
        ButtBot is an autonomous ground vehicle that drives around a given space and uses computer vision to identify and collect cigarette butts. The brain of the robot is a [<mark>NVIDIA Jetson Nano</mark>](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-nano/){:target="_blank"}. The smarts of the robot are written in <mark>Python</mark> and make use of many popular libraries. For the computer vision and deep learning we use <mark>OpenCV</mark>, <mark>TensorFlow</mark>, and <mark>Keras</mark>. The project also makes use of <mark>multi-threading</mark> and <mark>multi-processing</mark> to manage and coordinate the different functions of the robot. This is my fourth-year capstone project that I worked on with 4 of my peers, with myself and one other project member taking responsibility for all the software componenets.

    - layout: top-middle
      title: Calculux
      additional_links:
        - title: peter-dye/Calculux
          icon: fab fa-github
          url: github.com/peter-dye/Calculux
      quote: >
        Calculator Delux, the most convenient desktop calculator app for engineers.
      description: | # this will include new lines to allow paragraphs
        Calculux is a desktop calculator app I developed becuase existing apps did not provide the features that I wanted. Calculux allows you to access every single button on the calculator using only the numpad, Alt modifier, and the Control (Windows) or Command (MacOS) modifier keys. This eliminates slow and clumsy mouse movements. Calculux also implements math capabilities that most other off-the-shelf calculator apps don't, such as complex number calculations. I developed Calculux in <mark>Python</mark>, and used <mark>PyQt5</mark> to develop the graphical interface with the [<mark>Qt</mark>](https://www.qt.io/){:target="_blank"} framework. I used the [<mark>fman build system</mark>](https://build-system.fman.io/){:target="_blank"} to package the application and make installers for both Windows and MacOS. I learned a lot about desktop application development from this project, especially regarding packaging and distributing apps. I released Calculux as an open source project under the GNU GPL v3.

    - layout: top-middle
      title: Pong
      github: peter-dye/pong
      additional_links:
        - title: peter-dye/pong
          icon: fab fa-github
          url: github.com/peter-dye/pong
      quote: >
        Online mutliplayer implementation of the classic arcade game Pong.
      description: | # this will include new lines to allow paragraphs
        I built pong because I wanted to experiment with developing a real-time multiplayer game that is playable over the internet. In pong, anyone can create a game and send the code to their friend so they can join and battle it out... 70's style! I developed pong with <mark>JavaScript</mark>, using <mark>React</mark> for the frontend and <mark>Node.js</mark> for the backend. The content is served with <mark>Express</mark> and the real-time communication is implemented with <mark>Socket.io</mark>. Pong runs on an <mark>Azure</mark> server and is available for anyone to play. Checkout the GitHub link above to read more about the architecture and see the guide that I made or how to setup an Azure server to run the game.

    - layout: top-middle
      title: PD40
      additional_links:
        - title: peter-dye/pd40-keyboard
          icon: fab fa-github
          url: github.com/peter-dye/pd40-keyboard
      quote: >
        My 40% ortholinear low profile keyboard that I designed and built.
      description: | # this will include new lines to allow paragraphs
        The PD40 is a bluetooth keyboard that I designed and built from scratch. It is a handwired 40% ortholinear layout, and it uses Kailh Choc switches for a low profile (specifically linear red switches if you were wondering). The keyboard runs on an Adafruit Feather 32u4, and uses the [QMK](https://qmk.fm/){:target="_blank"} firmware written in <mark>C</mark>. This keyboard is highly optimized for writing code because it makes all the normal syntax characters available with minimal finger movement. I used [FreeCAD](https://www.freecadweb.org/){:target="_blank"} to design and <mark>3D print</mark> the top and bottom of the case. The switches are all handwired, which means I had to solder the diodes and wires to each switch individually to make the matrix. The QMK firmware is specifically designed for computer input devices, so all I had to do here was write the configuration code for a new keyboard implementation. I was new to the keyboard hobby when I built this so <mark>I wrote a detailed guide</mark> on how to build the PD40, which you can find in the GitHub repository.

################################################################################

- title: Experience
  layout: list
  content:

    - layout: left
      title: Brock Solutions
      sub_title: Software Developer
      caption: May 2021 - Present
      link: brocksolutions.com
      quote: >
        Brock Solutions is an engineering solutions and professional services company specializing in the design, build and implementation of real-time solutions for broad based industrial/manufacturing and transportation/logistics organizations globally.
      description: | # this will include new lines to allow paragraphs
        - Architected and developed automation tools for AutoCAD using C# and .NET.
        - Took the initiative to implement logging for the automation tools.
        - Refactored existing code base organization to bring it up to standard with .NET best practices.

    - layout: left
      title: Tidal Medical
      sub_title: Software Lead (Coop)
      caption: Sept 2020 - Dec 2020
      link: tidalmedical.com
      quote: >
       Tidal Medical is a dynamic new startup in the medical technology field.
      description: | # this will include new lines to allow paragraphs
        - Successfully lead software team by exceeding expectations with the final product that was developed.
        - Architected and developed a GUI application that interfaces with embedded hardware to reconstruct and dislay medical images in real time.
            - Used Python, Qt through PyQt5, and pyqtgraph, as well as [Cython](https://cython.org/){:target="_blank"} and multithreading for real time images.
        - Modelled advanced image reconstruction algorithms in MATLAB/[Octave](https://octave.sourceforge.io/){:target="_blank"}.
        - Developed fast embedded system communication to an FPGA using the [SPI](https://en.wikipedia.org/wiki/Serial_Peripheral_Interface){:target="_blank"} protocol.

    - layout: left
      title: Brock Solutions
      sub_title: Controls Engineering (Coop)
      caption: Sept - Dec 2019
      link: brocksolutions.com
      quote: >
       Brock Solutions is an engineering solutions and professional services company specializing in the design, build and implementation of real-time solutions for broad based industrial/manufacturing and transportation/logistics organizations globally.
      description: | # this will include new lines to allow paragraphs
        - Developed Python script to significantly speed up PLC tag generation process.
        - Learned about the whole software development cycle for PLCs.
        - Performed QA and controls systems validation with PICS and AutoMod simulation programs.
        - Gained lots of experience programming with Ladder Logic to solve a variety of controls problems.
        - Implemented controls solutions using inter-PLC communication and redundant PLC systems.

    - layout: left
      title: Smith + Andersen
      sub_title: Junior Electrical Designer (Coop)
      caption: Jan - Apr 2019
      link: smithandandersen.com
      quote: >
       Smith + Andersen is a trusted Canadian mechanical and electrical consultanting engineering firm, reaching new levels of engineering and design excellence in the communications, security, and audiovisual fields.
      description: | # this will include new lines to allow paragraphs
        - Developed communication techniques to manage competing deadlines through upwards management.
        -	Deepened experience in electrical system design techniques, as well as in the consulting industry as a whole.
        -	Performed site visits to map existing conditions and investigate design solutions.
        -	Expanded and improved on skills gained from working at Stantec.

    - layout: left
      title: Stantec
      sub_title: Electrical Design Assistant (Coop)
      caption: May - Aug 2018
      link: stantec.com
      quote: >
       Designers, engineers, scientists, and project managers, innovating together at the intersection of community, creativity, and client relationships. Designing with community in mind.
      description: | # this will include new lines to allow paragraphs
        -	Developed feeder size calculator in Excel to increase efficiency of feeder sizing by around 80%.
        -	Experience working on new construction and tenant fit-out for office, retail, warehouse, hospitals and airports.
        -	Designed building systems such as power, lighting, fire alarm and security in accordance with the OESC, OBC, and NFC.
        -	Well versed in modelling building electrical systems using Revit and AutoCAD.
        -	Coordinated with architects, interior designers, mechanical, and structural teams for seamless design.

    - layout: left
      title: NAV CANADA
      sub_title: Engineering Student (Coop)
      caption: Jan - Apr & Sept - Dec 2018
      link: navcanada.ca
      quote: >
       Canada's Air Navigation Service Provider, keeping airplanes safe from coast to coast.
      description: | # this will include new lines to allow paragraphs
        -	Developed and implemented an algorithm to graph data gathered from a precipitation sensor.
        -	Developed a system to record weather data from various sensors using a web-based environment on Raspberry Pi.
        -	Created and modified technical schematics in AutoCAD while adhering to company standards.
        -	Designed a power supply to be integrated into an existing system.
        -	Authored technical documentation for installation and upkeep of airport weather systems.

################################################################################

- title: Education
  layout: list
  content:
    - layout: left
      title: University of Waterloo
      sub_title: Bachelor of Applied Science <br/> Major in Electrical Engineering <br/> Option in Computer Engineering
      caption: Sept 2016 - Apr 2021
      quote: >
        Canada's most innovative university, with a world renowned engineering faculty, and a co-op program that is second to none.
      description: | # this will include new lines to allow paragraphs
        I majored in Electrical Engineering and completed an additional Option in Computer Engineering. This allowed me to gain valuable exposure to both hardware and software, although I focused on software for my upper-year courses. I enjoyed my academics and did well in them; I usually ranked near the top of my class. Have a look at my [transcript](../images/transcript.pdf){:target="_blank"} if you are interested!

        Outside of academics, I was heavily involved in campus life. I dedicated large amounts of time to the Engineering Society, and served as VP Finance where I managed our termly operating budget of approximately $80,000, along with other society operations. I also organized various events, was elected as a class Academic Representative, chaired Engineering Society meetings, and sat on the Engineering Society board of directors.

        My favourite invovlment at university has to be as an orientation leader. I was able to welcome multiple years of new students and help organize and run fun orientation weeks for everyone who participated.

        I also attended engineering conferences to broaden my knowledge and make new connections. They were:
          - Professional Engineers Ontario conference (provincial).
          - Canadian Federation of Engineering Students Congress (national).
            - Participated in the case study competition and placed second.
          - Conference for Sustainability in Engineering (national).
            - Participated in the case study competition and placed third.

################################################################################

- title: A Little More About Me
  layout: text
  content: | # this will include new lines to allow paragraphs
    Some of my other interests and hobbies are:
     - Flying airplanes and sailplanes; I have two pilots licenses!
     - Cooking and baking; I love trying new techniques and working with new ingredients!
     - Biking; especially mountain biking and downhilling!
     - Skiing; the bigger the mountain the better!
     - Reading and learning; I enjoy a good book, especially sci-fi, and love to investigate new things!

# Footer
footer_show_references: false

# Build settings
remote_theme: peter-dye/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
